name: Build, Test, and Publish NGINX Sleep Module

on:
  schedule:
    - cron: '0 6 * * *'
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'

env:
  DEFAULT_NGINX_INGRESS_TAG: 5.0.0-ubi

jobs:
  test-module:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run module tests
        run: |
          cd ngx_steadybit_sleep_module
          bash test-sleep-module.sh

  build-ubi:
    runs-on: ubuntu-latest
    needs: test-module
    strategy:
      matrix:
        tag: [ 5.0.0-ubi ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build UBI image
        run: |
          docker build \
            --build-arg NGINX_INGRESS_TAG=${{ matrix.tag }} \
            -f Dockerfile.ubi \
            -t ghcr.io/steadybit/nginx-ingress-with-steadybit-module:${{ github.ref_name }}-ubi-${{ matrix.tag }} .
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push UBI image
        run: |
          docker push ghcr.io/steadybit/nginx-ingress-with-steadybit-module:${{ github.ref_name }}-ubi-${{ matrix.tag }}

      - name: Tag and push default image for main branch
        if: github.ref == 'refs/heads/main' && matrix.tag == '5.0.0-ubi'
        run: |
          docker tag ghcr.io/steadybit/nginx-ingress-with-steadybit-module:${{ github.ref_name }}-ubi-${{ matrix.tag }} ghcr.io/steadybit/nginx-ingress-with-steadybit-module:${{ github.ref_name }}
          docker push ghcr.io/steadybit/nginx-ingress-with-steadybit-module:${{ github.ref_name }}


  build-community:
    runs-on: ubuntu-latest
    needs: test-module
    strategy:
      matrix:
        include:
          - base_tag: v1.13.0
            nginx_version: 1.27.1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build Community image
        run: |
          docker build \
            --build-arg BASE_TAG=${{ matrix.base_tag }} \
            --build-arg NGINX_VERSION=${{ matrix.nginx_version }} \
            -f Dockerfile.community \
            -t ghcr.io/steadybit/ingress-nginx-controller-with-steadybit-module:${{ github.ref_name }}-community-${{ matrix.base_tag }} .
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Community image
        run: |
          docker push ghcr.io/steadybit/ingress-nginx-controller-with-steadybit-module:${{ github.ref_name }}-community-${{ matrix.base_tag }}