name: Build and Publish NGINX Sleep Module

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nginx_ingress_tag: ['5.0.0-ubi']
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Run module tests
        run: |
          cd ngx_steadybit_sleep_module
          bash test-sleep-module.sh

      - name: Build in Docker
        run: |
          docker build \
            --build-arg NGINX_INGRESS_TAG=${{ matrix.nginx_ingress_tag }} \
            -f Dockerfile.runtime \
            -t ghcr.io/steadybit/nginx-ingress-with-steadybit-module:${{ github.ref_name }}-nginx-ingress-${{ matrix.nginx_ingress_tag }} .

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        run: |
          docker push ghcr.io/steadybit/nginx-ingress-with-steadybit-module:${{ github.ref_name }}-nginx-ingress-${{ matrix.nginx_ingress_tag }}