name: Build, Test, and Publish NGINX Sleep Module

on:
  schedule:
    - cron: '0 6 * * *'
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'

env:
  DEFAULT_NGINX_INGRESS_TAG: 5.0.0-ubi

permissions:
  contents: read
  packages: write

jobs:
  test-module:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run module tests
        run: |
          cd ngx_steadybit_sleep_module
          bash test-sleep-module.sh

  build-ubi:
    runs-on: ubuntu-latest
    needs: test-module
    strategy:
      matrix:
        tag: [ 5.0.0-ubi ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push UBI multi-arch image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.ubi
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            NGINX_INGRESS_TAG=${{ matrix.tag }}
          tags: |
            ghcr.io/steadybit/nginx-ingress-with-steadybit-module:${{ github.ref_name }}-ubi-${{ matrix.tag }}
      - name: Tag and push default image for main branch
        if: github.ref == 'refs/heads/main' && matrix.tag == '5.0.0-ubi'
        run: |
          docker buildx imagetools create \
            --tag ghcr.io/steadybit/nginx-ingress-with-steadybit-module:${{ github.ref_name }} \
            ghcr.io/steadybit/nginx-ingress-with-steadybit-module:${{ github.ref_name }}-ubi-${{ matrix.tag }}

  build-community:
    runs-on: ubuntu-latest
    needs: test-module
    strategy:
      matrix:
        include:
          - base_tag: v1.13.0
            nginx_version: 1.27.1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Community multi-arch image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.community
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            BASE_TAG=${{ matrix.base_tag }}
            NGINX_VERSION=${{ matrix.nginx_version }}
          tags: |
            ghcr.io/steadybit/ingress-nginx-controller-with-steadybit-module:${{ github.ref_name }}-community-${{ matrix.base_tag }}