name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libpcre3-dev zlib1g-dev libssl-dev curl bc

      - name: Run test script
        run: |
          cd ngx_steadybit_sleep_module
          bash test-sleep-module.sh 