name: ghcr-cleanup

on:
  workflow_dispatch: { }
  schedule:
    - cron: "0 8 * * 1"

jobs:
  ghcr-cleanup:
    name: Delete old container images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container: [ingress-nginx-controller-with-steadybit-module, nginx-ingress-with-steadybit-module]
    steps:
      - uses: vlaurin/action-ghcr-prune@v0.5.0
        with:
          token: ${{ secrets.GHCR_CLEANUP_PAT }}
          organization: steadybit
          container: ${{ matrix.container }}
          keep-younger-than: 1
          keep-last: 2
          keep-tags: |
            develop
            main
            latest
          keep-tags-regexes: "^v?(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$" #all semver
          prune-tags-regexes: "^[a-f0-9]{40}$" #all commit hashes
          prune-untagged: true
